name: CI

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '^1.22.5'
          cache: true

      - name: Fetch
        run: |
          rm -rf public/
          mkdir public
          go run . -o public/ sources.txt

      - name: Push
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add public/
          git commit -m "Updated at $(date '+%Y-%m-%d %H:%M:%S')"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
